"""initial schema - all 8 tables

Revision ID: b9fa54df5269
Revises: 
Create Date: 2026-07-13 13:23:09.944819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fa54df5269'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('land_holding_acres', sa.Float(), nullable=True),
    sa.Column('caste', sa.String(length=50), nullable=True),
    sa.Column('annual_income', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('is_bpl', sa.Boolean(), nullable=True),
    sa.Column('has_kisan_credit_card', sa.Boolean(), nullable=True),
    sa.Column('primary_crop', sa.String(length=100), nullable=True),
    sa.Column('irrigation_type', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_hash'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_farmer_profiles_caste', 'farmer_profiles', ['caste'], unique=False)
    op.create_index('ix_farmer_profiles_phone', 'farmer_profiles', ['phone'], unique=False)
    op.create_index('ix_farmer_profiles_state', 'farmer_profiles', ['state'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_celery_task_id', 'jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_status_run_at', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('ministries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_hindi', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_hindi', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_hindi', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('search_synonyms', sa.JSON(), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_schemes_content_hash', 'schemes', ['content_hash'], unique=False)
    op.create_index('ix_schemes_is_active', 'schemes', ['is_active'], unique=False)
    op.create_index('ix_schemes_ministry_id', 'schemes', ['ministry_id'], unique=False)
    op.create_index('ix_schemes_slug', 'schemes', ['slug'], unique=False)
    op.create_index('ix_schemes_url_hash', 'schemes', ['url_hash'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('query_raw', sa.Text(), nullable=False),
    sa.Column('query_normalized', sa.Text(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('top_scheme_ids', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_logs_created_at', 'search_logs', ['created_at'], unique=False)
    op.create_index('ix_search_logs_farmer_id', 'search_logs', ['farmer_id'], unique=False)
    op.create_index('ix_search_logs_session_id', 'search_logs', ['session_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('format', sa.Enum('HTML', 'PDF', 'CSV', 'JSON', 'XLSX', 'DOCX', 'XML', name='sourceformat'), nullable=False),
    sa.Column('crawl_interval_hours', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rps', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('respect_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    op.create_index('ix_sources_is_active', 'sources', ['is_active'], unique=False)
    op.create_index('ix_sources_next_crawl_at', 'sources', ['next_crawl_at'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='crawljobstatus'), nullable=False),
    sa.Column('job_type', sa.Enum('FULL', 'INCREMENTAL', 'MANUAL', name='crawljobtype'), nullable=False),
    sa.Column('urls_discovered', sa.Integer(), nullable=False),
    sa.Column('urls_crawled', sa.Integer(), nullable=False),
    sa.Column('schemes_upserted', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crawl_jobs_celery_task_id', 'crawl_jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_crawl_jobs_scheduled_at', 'crawl_jobs', ['scheduled_at'], unique=False)
    op.create_index('ix_crawl_jobs_source_id', 'crawl_jobs', ['source_id'], unique=False)
    op.create_index('ix_crawl_jobs_status', 'crawl_jobs', ['status'], unique=False)
    op.create_table('eligibility_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('overall_result', sa.Enum('MET', 'NOT_MET', 'NA', name='eligibilityresult'), nullable=False),
    sa.Column('criteria_results', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id', 'scheme_id', name='uq_eligibility_farmer_scheme')
    )
    op.create_index('ix_eligibility_records_farmer_id', 'eligibility_records', ['farmer_id'], unique=False)
    op.create_index('ix_eligibility_records_overall_result', 'eligibility_records', ['overall_result'], unique=False)
    op.create_index('ix_eligibility_records_scheme_id', 'eligibility_records', ['scheme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eligibility_records_scheme_id', table_name='eligibility_records')
    op.drop_index('ix_eligibility_records_overall_result', table_name='eligibility_records')
    op.drop_index('ix_eligibility_records_farmer_id', table_name='eligibility_records')
    op.drop_table('eligibility_records')
    op.drop_index('ix_crawl_jobs_status', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_source_id', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_scheduled_at', table_name='crawl_jobs')
    op.drop_index('ix_crawl_jobs_celery_task_id', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index('ix_sources_next_crawl_at', table_name='sources')
    op.drop_index('ix_sources_is_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_search_logs_session_id', table_name='search_logs')
    op.drop_index('ix_search_logs_farmer_id', table_name='search_logs')
    op.drop_index('ix_search_logs_created_at', table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index('ix_schemes_url_hash', table_name='schemes')
    op.drop_index('ix_schemes_slug', table_name='schemes')
    op.drop_index('ix_schemes_ministry_id', table_name='schemes')
    op.drop_index('ix_schemes_is_active', table_name='schemes')
    op.drop_index('ix_schemes_content_hash', table_name='schemes')
    op.drop_table('schemes')
    op.drop_table('ministries')
    op.drop_index('ix_jobs_status_run_at', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_index('ix_jobs_celery_task_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_farmer_profiles_state', table_name='farmer_profiles')
    op.drop_index('ix_farmer_profiles_phone', table_name='farmer_profiles')
    op.drop_index('ix_farmer_profiles_caste', table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    # ### end Alembic commands ###
